# Generated by Django 4.2.5 on 2023-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.PositiveIntegerField(unique=True)),
                ('questions', models.JSONField(default=list)),
                ('answers', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['telegram_chat_id'], name='telegram_chat_id_idx')],
            },
        ),
    ]
